# Generated by Django 5.1.6 on 2025-05-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='url_video',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complementarymaterial',
            name='tipo',
            field=models.CharField(choices=[('file', 'Arquivo'), ('link', 'Link Externo')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duração em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('canceled', 'Cancelado')], default='pending', max_length=10),
        ),
    ]
