# Generated by Django 5.1.6 on 2025-05-23 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_url_video_lesson_video_url_comments_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mercado Pago', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Ambiente de Testes')),
                ('production_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('production_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento',
                'verbose_name_plural': 'Configurações de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='purchases',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payer_document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Cartão de Crédito'), ('bank_slip', 'Boleto'), ('pix', 'PIX')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchases',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('in_process', 'Em Processamento'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('canceled', 'Cancelado'), ('in_mediation', 'Em Mediação'), ('charged_back', 'Estornado')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Cartão de Crédito'), ('bank_slip', 'Boleto'), ('pix', 'PIX')], max_length=20, null=True)),
                ('installments', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Checkout',
                'verbose_name_plural': 'Sessões de Checkout',
            },
        ),
    ]
