# Generated by Django 5.2.4 on 2025-08-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_paymentsettings_purchases_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='production_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret para validação de webhooks em produção', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='sandbox_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret para validação de webhooks em sandbox', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['active', '-creation_date'], name='products_co_active_41f072_idx'),
        ),
    ]
