# Generated by Django 5.2.4 on 2025-08-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_paymentsettings_production_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='upload_status',
            field=models.CharField(choices=[('ready', 'Pronto'), ('pending', 'Pendente'), ('uploading', 'Enviando'), ('processing', 'Processando'), ('error', 'Erro')], default='ready', help_text='Status do upload do vídeo', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(choices=[('direct', 'URL Direta'), ('vimeo', 'Vimeo'), ('youtube', 'YouTube')], default='direct', help_text='Provedor de vídeo', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_video_id',
            field=models.CharField(blank=True, help_text='ID do vídeo no Vimeo (se aplicável)', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL direta do vídeo (compatibilidade)', null=True),
        ),
    ]
